source: src
target: www
indexTemplate: src/index-template.html
postTemplate: src/post-template.html
overwrite: false
versionFile: package.json
execute: git add . && git commit -a -m "ðŸ’¬ blog update `date`" && git push